import React, { useState } from 'react';
import { TabType, ExportSettings } from './types';
import { INITIAL_MARKDOWN, INITIAL_CSS, PRESET_THEMES } from './constants';
import { refineMarkdown, suggestCSS } from './services/geminiService';
import { downloadHTML, downloadDOCX, downloadPDF } from './services/exportService';
import Editor from './components/Editor';
import Preview from './components/Preview';
import { marked } from 'marked';

interface Notification {
  message: string;
  type: 'success' | 'error' | 'info';
  id: number;
}

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<TabType>('markdown');
  const [markdown, setMarkdown] = useState(INITIAL_MARKDOWN);
  const [css, setCss] = useState(INITIAL_CSS);
  const [js, setJs] = useState('');
  const [isExportingPDF, setIsExportingPDF] = useState(false);
  const [isExportingWord, setIsExportingWord] = useState(false);
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [settings, setSettings] = useState<ExportSettings>({
    pageSize: 'A4',
    orientation: 'portrait',
    margin: 20,
    theme: 'github-light',
    enableJS: true,
    previewMode: 'responsive'
  });

  const notify = (message: string, type: 'success' | 'error' | 'info' = 'info') => {
    const id = Date.now();
    setNotifications(prev => [...prev, { message, type, id }]);
    setTimeout(() => {
      setNotifications(prev => prev.filter(n => n.id !== id));
    }, 4000);
  };

  const handleFetchGithub = async () => {
    const url = prompt("Enter GitHub Repository URL (e.g. facebook/react):");
    if (!url) return;
    
    try {
      const repo = url.replace('https://github.com/', '').trim();
      notify(`Fetching README from ${repo}...`, 'info');
      const response = await fetch(`https://api.github.com/repos/${repo}/readme`, {
        headers: { 'Accept': 'application/vnd.github.raw' }
      });
      if (response.ok) {
        const text = await response.text();
        setMarkdown(text);
        notify('README fetched successfully!', 'success');
      } else {
        notify('Could not find README.', 'error');
      }
    } catch (err) {
      notify('Error fetching from GitHub.', 'error');
    }
  };

  const handleAiRefine = async () => {
    if (!aiPrompt) return;
    setIsAiLoading(true);
    try {
      if (activeTab === 'markdown') {
        const refined = await refineMarkdown(markdown, aiPrompt);
        setMarkdown(refined);
        notify('Refined by AI!', 'success');
      } else if (activeTab === 'css') {
        const newCss = await suggestCSS(markdown, aiPrompt);
        setCss(newCss);
        notify('CSS generated by AI!', 'success');
      }
      setAiPrompt('');
    } catch (err) {
      notify('AI refinement failed.', 'error');
    } finally {
      setIsAiLoading(false);
    }
  };

  const handleThemeChange = (themeId: string) => {
    const theme = PRESET_THEMES.find(t => t.id === themeId);
    if (theme) {
      setCss(theme.css);
      setSettings(prev => ({ ...prev, theme: themeId }));
      notify(`Theme switched to ${theme.name}`, 'info');
    }
  };

  const getCleanHtmlForExport = () => {
    try {
      const htmlBody = marked.parse(markdown);
      if (!htmlBody) throw new Error("Document is empty");
      
      const isDark = settings.theme.includes('dark') || settings.theme.includes('terminal');
      
      return `
        <div class="readme-pro-export-wrapper">
          <style>
            html, body { 
              background-color: white !important; 
              margin: 0; 
              padding: 0; 
              min-height: 100vh;
              visibility: visible !important;
              display: block !important;
            }
            
            .readme-pro-export-wrapper {
              width: 100%;
              min-height: 100vh !important;
              background-color: ${isDark ? '#0d1117' : '#ffffff'} !important;
              color: ${isDark ? '#c9d1d9' : '#24292e'} !important;
              box-sizing: border-box;
              padding: 30mm;
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
              -webkit-print-color-adjust: exact;
              print-color-adjust: exact;
              display: block !important;
              visibility: visible !important;
            }

            .markdown-body { 
              width: 100%; 
              display: block !important; 
            }
            .markdown-body img { max-width: 100%; height: auto; display: block; margin: 1em 0; }
            .markdown-body pre { background: ${isDark ? '#161b22' : '#f6f8fa'}; padding: 16px; border-radius: 6px; border: 1px solid ${isDark ? '#30363d' : '#dfe2e5'}; }

            /* User's Injected CSS */
            ${css}
          </style>
          <div class="markdown-body" style="display:block; width:100%;">
            ${htmlBody}
          </div>
        </div>
      `;
    } catch (e) {
      console.error("Export HTML generation error", e);
      return `<div style="color:red">Rendering error. Content might be missing.</div>`;
    }
  };

  const handleExportPDF = async () => {
    if (isExportingPDF || !markdown.trim()) {
      if (!markdown.trim()) notify('Cannot export empty document.', 'error');
      return;
    }
    
    setIsExportingPDF(true);
    notify('Capturing high-fidelity PDF...', 'info');
    
    try {
      const html = getCleanHtmlForExport();
      await downloadPDF(html, 'readme-pro.pdf', {
        format: settings.pageSize,
        orientation: settings.orientation
      });
      notify('PDF Download Complete!', 'success');
    } catch (e: any) {
      console.error(e);
      notify(e.message || 'PDF export failed.', 'error');
    } finally {
      setIsExportingPDF(false);
    }
  };

  const handleExportWord = () => {
    setIsExportingWord(true);
    notify('Building Word package...', 'info');
    try {
      const htmlBody = marked.parse(markdown);
      downloadDOCX(htmlBody as string, css, 'readme-pro.doc');
      notify('Word export successful!', 'success');
    } catch (e: any) {
      notify('Word export failed.', 'error');
    } finally {
      setIsExportingWord(false);
    }
  };

  const handleExportHTML = () => {
    try {
      notify('Exporting HTML bundle...', 'info');
      const htmlBody = marked.parse(markdown);
      const isDark = settings.theme.includes('dark') || settings.theme.includes('terminal');
      const fullHtml = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>README Export</title><style>body{background-color:${isDark ? '#0d1117' : '#fff'};color:${isDark ? '#c9d1d9' : '#24292e'};padding:40px;margin:0;font-family:sans-serif;}${css}</style></head><body><div class="markdown-body">${htmlBody}</div></body></html>`;
      downloadHTML(fullHtml, 'readme-pro.html');
      notify('HTML file ready!', 'success');
    } catch (e: any) {
      notify('HTML export failed.', 'error');
    }
  };

  const handlePrint = () => {
    notify('Launching Print Preview...', 'info');
    const iframe = document.createElement('iframe');
    iframe.style.display = 'none';
    document.body.appendChild(iframe);
    const doc = iframe.contentWindow?.document;
    if (doc) {
      doc.open();
      const htmlBody = marked.parse(markdown);
      doc.write(`<html><head><style>body{padding:40px;font-family:sans-serif;}${css}</style></head><body><div class="markdown-body">${htmlBody}</div></body></html>`);
      doc.close();
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
      setTimeout(() => document.body.removeChild(iframe), 2000);
    }
  };

  return (
    <div className="flex flex-col h-screen overflow-hidden relative selection:bg-blue-500/30 font-sans">
      {/* Notifications */}
      <div className="fixed top-20 right-6 z-[100] flex flex-col gap-2 w-80 pointer-events-none">
        {notifications.map(n => (
          <div key={n.id} className={`pointer-events-auto p-4 rounded-xl shadow-2xl border backdrop-blur-md transition-all animate-slide-in flex items-start gap-3 ${
            n.type === 'success' ? 'bg-emerald-900/80 border-emerald-500/50 text-emerald-100' :
            n.type === 'error' ? 'bg-rose-900/80 border-rose-500/50 text-rose-100' : 'bg-slate-800/90 border-slate-600/50 text-slate-100'
          }`}>
            <div className="mt-0.5">
              {n.type === 'success' && <i className="fa-solid fa-circle-check text-emerald-400"></i>}
              {n.type === 'error' && <i className="fa-solid fa-circle-exclamation text-rose-400"></i>}
              {n.type === 'info' && <i className="fa-solid fa-gear fa-spin text-blue-400"></i>}
            </div>
            <p className="text-sm font-medium leading-relaxed">{n.message}</p>
          </div>
        ))}
      </div>

      <header className="h-16 bg-slate-900 border-b border-slate-800 px-6 flex items-center justify-between z-10 shadow-2xl">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gradient-to-tr from-blue-600 to-indigo-600 rounded-xl flex items-center justify-center text-white shadow-lg shadow-blue-500/20">
            <i className="fa-solid fa-bolt text-xl"></i>
          </div>
          <div className="flex flex-col">
            <h1 className="font-black text-lg tracking-tight leading-tight">README<span className="text-blue-500">PRO</span></h1>
            <span className="text-[9px] text-slate-500 font-bold uppercase tracking-widest leading-none">Safe-Render V2.8</span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button onClick={handleFetchGithub} className="hidden lg:flex items-center gap-2 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs font-bold border border-slate-700 transition-all active:scale-95">
            <i className="fa-brands fa-github"></i> FETCH
          </button>
          <button onClick={handlePrint} className="hidden md:flex items-center gap-2 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs font-bold border border-slate-700 transition-all active:scale-95">
            <i className="fa-solid fa-print"></i> PRINT
          </button>
          <div className="hidden md:block h-6 w-[1px] bg-slate-700 mx-1"></div>
          <button onClick={handleExportHTML} className="group flex items-center gap-2 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-100 rounded-lg text-xs font-bold border border-slate-700 transition-all active:scale-95">
             <i className="fa-solid fa-code text-blue-400 group-hover:scale-110 transition-transform"></i> HTML
          </button>
          <button onClick={handleExportWord} disabled={isExportingWord} className="group flex items-center gap-2 px-3 py-1.5 bg-sky-700 hover:bg-sky-600 text-white rounded-lg text-xs font-bold transition-all disabled:opacity-50 active:scale-95">
            {isExportingWord ? <i className="fa-solid fa-spinner fa-spin"></i> : <i className="fa-solid fa-file-word text-white/80 group-hover:scale-110 transition-transform"></i>} WORD
          </button>
          <button onClick={handleExportPDF} disabled={isExportingPDF} className="group flex items-center gap-2 px-4 py-1.5 bg-rose-600 hover:bg-rose-500 text-white rounded-lg text-xs font-black transition-all shadow-lg shadow-rose-900/20 disabled:opacity-50 active:scale-95">
            {isExportingPDF ? <i className="fa-solid fa-circle-notch fa-spin"></i> : <i className="fa-solid fa-file-pdf text-white group-hover:scale-110 transition-transform"></i>} DOWNLOAD PDF
          </button>
        </div>
      </header>

      <main className="flex-1 flex overflow-hidden bg-slate-950 p-4 gap-4">
        <div className="w-1/2 flex flex-col gap-4">
          <div className="flex gap-1.5 p-1 bg-slate-900 border border-slate-800 rounded-xl w-fit">
            {(['markdown', 'css', 'js', 'settings'] as TabType[]).map(tab => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-4 py-1.5 rounded-lg text-[11px] font-black uppercase tracking-wider transition-all ${
                  activeTab === tab ? 'bg-blue-600 text-white shadow-md' : 'text-slate-500 hover:text-slate-300'
                }`}
              >
                {tab}
              </button>
            ))}
          </div>

          <div className="flex-1 relative overflow-hidden bg-slate-900 rounded-2xl border border-slate-800 shadow-2xl">
            {activeTab !== 'settings' ? (
              <Editor 
                language={activeTab === 'js' ? 'javascript' : activeTab as any} 
                value={activeTab === 'markdown' ? markdown : activeTab === 'css' ? css : js} 
                onChange={activeTab === 'markdown' ? setMarkdown : activeTab === 'css' ? setCss : setJs} 
                label={activeTab.toUpperCase()} 
              />
            ) : (
              <div className="p-8 flex flex-col gap-8 text-slate-300 overflow-y-auto custom-scrollbar h-full">
                <div>
                  <h3 className="text-white text-lg font-black flex items-center gap-3">
                    <i className="fa-solid fa-sliders text-blue-500"></i> EXPORT SETTINGS
                  </h3>
                  <p className="text-xs text-slate-500 mt-1 font-medium">Fine-tune your document for professional output.</p>
                </div>

                <div className="grid grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label className="text-[10px] text-slate-500 font-black uppercase tracking-widest">Page Format</label>
                    <select value={settings.pageSize} onChange={(e) => setSettings({...settings, pageSize: e.target.value as any})} className="w-full bg-slate-800 border border-slate-700 rounded-xl p-3 text-sm focus:ring-2 focus:ring-blue-500 outline-none transition-all">
                      <option>A4</option><option>Letter</option>
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] text-slate-500 font-black uppercase tracking-widest">Orientation</label>
                    <select value={settings.orientation} onChange={(e) => setSettings({...settings, orientation: e.target.value as any})} className="w-full bg-slate-800 border border-slate-700 rounded-xl p-3 text-sm focus:ring-2 focus:ring-blue-500 outline-none transition-all">
                      <option value="portrait">Portrait</option><option value="landscape">Landscape</option>
                    </select>
                  </div>
                </div>

                <div className="space-y-3">
                  <label className="text-[10px] text-slate-500 font-black uppercase tracking-widest">Visual Presets</label>
                  <div className="grid grid-cols-3 gap-2">
                    {PRESET_THEMES.map(theme => (
                      <button key={theme.id} onClick={() => handleThemeChange(theme.id)} className={`px-4 py-3 rounded-xl text-[10px] font-black uppercase border transition-all ${settings.theme === theme.id ? 'border-blue-500 bg-blue-500/10 text-blue-400 shadow-[0_0_15px_-5px_rgba(59,130,246,0.3)]' : 'border-slate-800 bg-slate-800/50 text-slate-500 hover:border-slate-700 hover:text-slate-300'}`}>
                        {theme.name}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="pt-8 border-t border-slate-800 flex flex-col gap-4">
                  <button onClick={handleExportPDF} disabled={isExportingPDF} className="w-full group py-5 bg-gradient-to-r from-rose-600 to-rose-700 hover:from-rose-500 text-white rounded-2xl font-black flex items-center justify-center gap-3 transition-all shadow-lg shadow-rose-900/20 active:scale-95 disabled:opacity-50">
                    {isExportingPDF ? <i className="fa-solid fa-spinner fa-spin text-xl"></i> : <i className="fa-solid fa-file-pdf text-xl group-hover:scale-110 transition-transform"></i>}
                    GENERATE PDF DOCUMENT
                  </button>
                  <div className="grid grid-cols-2 gap-4">
                    <button onClick={handleExportWord} disabled={isExportingWord} className="py-4 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl font-bold flex items-center justify-center gap-2 border border-slate-700 transition-all">
                      <i className="fa-solid fa-file-word text-sky-500"></i> Word (.doc)
                    </button>
                    <button onClick={handleExportHTML} className="py-4 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl font-bold flex items-center justify-center gap-2 border border-slate-700 transition-all">
                      <i className="fa-solid fa-code text-emerald-500"></i> Static HTML
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>

          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-2.5 flex gap-3 items-center shadow-2xl focus-within:border-blue-500/50 transition-colors">
            <div className="w-8 h-8 rounded-lg bg-blue-500/10 flex items-center justify-center text-blue-500">
              <i className="fa-solid fa-wand-magic-sparkles"></i>
            </div>
            <input 
              type="text" 
              placeholder="Magic Refiner: 'modern minimal white' or 'dark futuristic'..." 
              className="flex-1 bg-transparent border-none text-sm text-slate-300 outline-none placeholder:text-slate-600" 
              value={aiPrompt} 
              onChange={(e) => setAiPrompt(e.target.value)} 
              onKeyDown={(e) => e.key === 'Enter' && handleAiRefine()} 
            />
            <button 
              onClick={handleAiRefine} 
              disabled={isAiLoading || !aiPrompt} 
              className="px-6 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-black transition-all disabled:opacity-50 active:scale-95 shadow-lg shadow-blue-500/10"
            >
              {isAiLoading ? 'GENERATING...' : 'APPLY MAGIC'}
            </button>
          </div>
        </div>

        <div className="w-1/2 flex flex-col gap-4">
          <div className="flex items-center justify-between px-2 h-10">
            <h2 className="text-slate-500 text-[10px] font-black uppercase tracking-[0.2em] flex items-center gap-2">
              <i className="fa-solid fa-circle-play text-blue-500 animate-pulse"></i> LIVE PREVIEW ENGINE
            </h2>
            <div className="flex bg-slate-900 p-1 rounded-xl border border-slate-800 shadow-lg">
              <button 
                onClick={() => setSettings(prev => ({ ...prev, previewMode: 'responsive' }))} 
                className={`px-4 py-1 rounded-lg text-[10px] font-black tracking-wider transition-all ${settings.previewMode === 'responsive' ? 'bg-blue-600 text-white shadow-sm' : 'text-slate-500 hover:text-slate-300'}`}
              >
                FLUID
              </button>
              <button 
                onClick={() => setSettings(prev => ({ ...prev, previewMode: 'page' }))} 
                className={`px-4 py-1 rounded-lg text-[10px] font-black tracking-wider transition-all ${settings.previewMode === 'page' ? 'bg-blue-600 text-white shadow-sm' : 'text-slate-500 hover:text-slate-300'}`}
              >
                PAGE
              </button>
            </div>
          </div>
          <div className="flex-1 drop-shadow-[0_20px_50px_rgba(0,0,0,0.5)]">
            <Preview 
              markdown={markdown} 
              css={css} 
              js={js} 
              enableJS={settings.enableJS} 
              mode={settings.previewMode} 
              pageSize={settings.pageSize} 
            />
          </div>
        </div>
      </main>

      <footer className="h-8 bg-slate-900 border-t border-slate-800 px-6 flex items-center justify-between text-[10px] text-slate-500 font-bold uppercase tracking-widest">
        <div className="flex gap-6">
           <span className="flex items-center gap-2"><i className="fa-solid fa-align-left opacity-50"></i> {markdown.length} CHRS</span>
           <span className="flex items-center gap-2"><i className="fa-solid fa-code-branch opacity-50"></i> {css.split('\n').length} STYLE RULES</span>
        </div>
        <div className="flex items-center gap-4">
          <span className="bg-slate-800 px-3 py-1 rounded-full border border-slate-700 text-slate-400">ENGINE STATUS: STEADY</span>
          <span className="text-emerald-500 flex items-center gap-1.5 font-bold"><i className="fa-solid fa-check-circle"></i> SYSTEM ONLINE</span>
        </div>
      </footer>
    </div>
  );
};

export default App;